/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemInfo */

#ifndef _Included_SystemInfo
#define _Included_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemInfo
 * Method:    get_info
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SystemInfo_get_1info
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
